# Generated by Django 5.0.4 on 2024-04-30 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("medico", "0001_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A", "Agendada"),
                            ("F", "Finalizada"),
                            ("C", "Cancelada"),
                            ("I", "Iniciada"),
                        ],
                        default="A",
                        max_length=1,
                    ),
                ),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "data_aberta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="medico.datasabertas",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DadosPaciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cpf",
                    models.CharField(blank=True, max_length=14, null=True, unique=True),
                ),
                (
                    "cns",
                    models.CharField(blank=True, max_length=25, null=True, unique=True),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "mother_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.userprofile",
                    ),
                ),
            ],
        ),
    ]
