# Generated by Django 5.0.4 on 2024-04-30 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=30)),
                ("documento", models.FileField(upload_to="documentos")),
            ],
        ),
        migrations.CreateModel(
            name="Especialidades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("especialidade", models.CharField(max_length=100)),
                ("icone", models.ImageField(blank=True, null=True, upload_to="icones")),
            ],
        ),
        migrations.CreateModel(
            name="DadosMedico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crm", models.CharField(max_length=30)),
                ("cedula_identidade_medica", models.ImageField(upload_to="cim")),
                ("descricao", models.TextField(blank=True, null=True)),
                ("valor_consulta", models.FloatField(default=100)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DatasAbertas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateTimeField()),
                ("agendado", models.BooleanField(default=False)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.userprofile",
                    ),
                ),
            ],
        ),
    ]
