# Generated by Django 5.0.4 on 2024-04-30 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("medico", "0001_initial"),
        ("paciente", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="consulta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="paciente.consulta"
            ),
        ),
        migrations.AddField(
            model_name="dadosmedico",
            name="especialidade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="medico.especialidades",
            ),
        ),
    ]
