# Generated by Django 5.0.4 on 2024-04-17 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medico", "0003_alter_datasabertas_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasabertas",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="medico",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
