# Generated by Django 5.0.4 on 2024-04-17 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medico", "0005_alter_dadosmedico_user_alter_datasabertas_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="dadosmedico",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="medico_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
