# Generated by Django 5.0.4 on 2024-04-30 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("cep", models.CharField(max_length=15)),
                ("rua", models.CharField(max_length=100)),
                ("bairro", models.CharField(max_length=100)),
                ("numero", models.IntegerField()),
                ("rg", models.ImageField(upload_to="rgs")),
                ("foto", models.ImageField(upload_to="fotos_perfil")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
